### PR TITLE
Fix missing define

### PR DESCRIPTION
**Pull request by sphawk**
add missing define NOWIDE_USE_WCHAR_OVERLOADS on standalone

### CODE REVIEW

**Comment by Flamefire** [comment]
Thanks for catching this. I'll see how I can avoid such issues in the future.

However all PRs should be against the `develop` branch. The `standalone` branch is auto-generated from that.

**Comment by sphawk** [comment]
I found it from using nowide::ifstream
there is "#if NOWIDE_USE_WCHAR_OVERLOADS"
and occured warning, and my compilation setting has warning as error.

May I close this pull request? or please close this.
Thanks.

**Comment by Flamefire** [comment]
Ok thanks! I assume you refer to `-Wundef` as the warning that occurs. I'll include that in the CI tests and make sure the define is properly set.

**Comment by Flamefire** [comment]
The standalone branch was just updated after merging the fix which now includes this define: https://github.com/boostorg/nowide/blob/standalone/include/nowide/config.hpp#L73-L79

I hope this works for you and thanks for reporting this!

**Comment by sphawk** [comment]
@Flamefire It works! thanks a lot!

**Pull request closed without merging**
